const Language = {
    code: 'en',
    created_at: '2021-11-08T13:01:24.000000Z',
    id: 1,
    l1: 'Find Your Dream Job',
    l10: 'Employer',
    l100: 'Hire Now',
    l101: 'Old',
    l102: 'Top Categories',
    l103: 'Popular Companies',
    l104: 'Jobs',
    l105: 'View All',
    l106: 'Occupation',
    l107: 'Add',
    l108: 'Add Your Education',
    l109: 'Is Continue',
    l11: 'Email',
    l110: 'Start Date',
    l111: 'End Date',
    l112: 'Company Name',
    l113: 'Company Address',
    l114: 'Project Link',
    l115: 'Optional',
    l116: 'Status',
    l117: 'Completed',
    l118: 'Bookmarks Not Found',
    l119: 'Filter',
    l12: 'Password',
    l120: 'Clear',
    l121: 'No',
    l122: 'Seeker',
    l123: 'Nokri',
    l124: 'Apply for This Job',
    l125: 'Occupation Not register',
    l126: 'Applied',
    l127: 'Save',
    l128: 'Apply',
    l129: 'Salary Type',
    l13: 'Forgot Password',
    l130: 'Job Type',
    l131: 'Salary Range',
    l132: 'Delete',
    l133: 'Edit',
    l134: 'Please purchase subscription for post jobs',
    l135: 'Password Update successfully',
    l136: 'Something went wrong try again.',
    l137: 'Create',
    l138: 'Your new password must be different from previous used password',
    l139: 'Please enter',
    l14: 'Login',
    l140: 'Name',
    l141: 'Password should be contain 8 digits at least',
    l142: 'Password are not matched',
    l143: 'New',
    l144: 'Right',
    l145: 'Modified On',
    l146: 'Post Job',
    l147: 'Enter Job Details',
    l148: 'Available Vacancies',
    l149: 'Please purchase subscription for post jobs',
    l15: 'With',
    l150: 'Please update your profile & For post job profile progress should be 70% or above',
    l151: 'No job is remaining in your purchased subscription Please Purchase Subscription Or Renew it.',
    l152: 'Select Sub Category',
    l153: 'Select Category',
    l154: 'Job Description',
    l155: 'Msg',
    l156: 'Job High Light',
    l157: 'Industry Type',
    l158: 'Functional Area',
    l159: 'Role',
    l16: "Don't have an account",
    l160: 'Skills Required',
    l161: 'Requirements',
    l162: 'Info',
    l163: 'Company',
    l164: 'Web Site',
    l165: 'Title',
    l166: 'Please select start date',
    l167: 'Please select end date',
    l168: 'Time period not valid',
    l169: "Start and end date can't be same",
    l17: 'Sign Up',
    l170: 'Please enter company name',
    l171: 'Please enter Role',
    l172: 'Please enter valid link',
    l173: 'Continue',
    l174: 'Completed',
    l175: 'Please enter job title',
    l176: 'Please select salary type',
    l177: 'Please select job type',
    l178: 'Please enter role',
    l179: 'Please enter education',
    l18: 'Welcome To',
    l180: 'Please enter  requirements',
    l181: 'Please enter description',
    l182: 'Please add 1 skill at least',
    l183: 'Per Week',
    l184: 'Per Month',
    l185: 'Part Time',
    l186: 'Full Time',
    l187: 'Occupation Not Registered',
    l188: 'All Categories',
    l189: 'All Categories',
    l19: 'Full Name',
    l190: 'Number',
    l191: 'Vacancies',
    l192: 'Developer',
    l193: 'Salary',
    l194: 'Not Linked Yet',
    l195: "Don't now how open this url :",
    l196: 'This email already register as Jobseeker',
    l197: 'This email already register as Employer',
    l198: 'Please enter userName',
    l199: 'OK',
    l2: 'Search and find your dream job easily and quickly',
    l20: 'Confirm Password',
    l200: 'OTP',
    l201: 'Jop Post Successfully',
    l202: "You can't select passed date's",
    l203: 'Select Interview Time',
    l204: 'Please Select Valid Date',
    l205: 'Sorry! This Employer has not uploaded introduction video yet.',
    l206: 'Sorry! This Seeker has not uploaded introduction video yet.',
    l207: 'Update successfully',
    l208: 'Job Update successfully',
    l209: 'Jop Posted Successfully',
    l21: 'Sign Up',
    l210: 'Click + to',
    l211: 'Already have an account?',
    l212: 'Video File should not be greater then 2mb',
    l213: 'Create Password',
    l214: 'Thank You. for Subscription',
    l215: 'Applied Successfully',
    l216: 'Session Expire. Please Login Again ',
    l22: 'Enter your register email below to receive password reset instructions',
    l23: 'Send',
    l24: 'Email Not Found',
    l25: 'Enter Otp Code',
    l26: 'Enter the Otp Code that you received on your email',
    l27: 'Verify',
    l28: 'Check Your Email',
    l29: 'We have send an password reset link on your email',
    l3: 'Get Your Dream Job',
    l30: 'OTP Not match Please try again',
    l31: 'Home',
    l32: 'Explore',
    l33: 'Favourites',
    l34: 'My Jobs',
    l35: 'Job Requests',
    l36: 'Profile',
    l37: 'Subscription',
    l38: 'Interviews',
    l39: 'My Posted Jobs',
    l4: 'Get Your Dream Job and start working in an new company',
    l40: 'Notifications',
    l41: 'Interview Invites',
    l42: 'Settings',
    l43: 'Sign Out',
    l44: 'Profile Progress',
    l45: 'View Profile',
    l46: 'Request Interview',
    l47: 'Chat',
    l48: 'Introduction video',
    l49: 'About',
    l5: 'Join and Start Your Work',
    l50: 'Language',
    l51: 'Skill',
    l52: 'Education',
    l53: 'Experience',
    l54: 'Work',
    l55: 'Candidate Profile',
    l56: 'Reviews',
    l57: 'No Reviews Found',
    l58: 'Give Review',
    l59: 'Profile',
    l6: 'Start Working With Your Team in your new marketplace',
    l60: 'Edit profile',
    l61: 'Completion Status',
    l62: 'Profile Complete',
    l63: 'Basic Information',
    l64: 'Visible',
    l65: 'Non Visible',
    l66: 'Company Name',
    l67: 'Address',
    l68: 'Phone',
    l69: 'Your',
    l7: 'Nokri Login',
    l70: 'Link',
    l71: 'Select Video',
    l72: 'Candidate',
    l73: 'Search Here',
    l74: 'Description',
    l75: 'Total Jobs',
    l76: 'Notification Not Found',
    l77: 'Please Purchase Subscription For Post Jobs',
    l78: 'Name On Card',
    l79: 'Card Number',
    l8: 'Login With Your Nokri',
    l80: 'Expiration',
    l81: 'Month',
    l82: 'Year',
    l83: 'Pay Now',
    l84: 'Successfully',
    l85: 'You Have Successfully Purchased A Subscription',
    l86: 'Active',
    l87: 'Posted',
    l88: 'Remain',
    l89: 'Please Update Your Profile',
    l9: 'Job Seeker',
    l90: 'Profile Update Successfully',
    l91: 'Select Interview Time',
    l92: 'Date',
    l93: 'Time',
    l94: 'Send',
    l95: 'Close',
    l96: 'Request',
    l97: 'Interview Schedule Successfully',
    l98: 'Invited',
    l99: 'Re Schedule',
    name: 'English',
    updated_at: '2021-11-08T13:01:24.000000Z',
};

export default Language;
